name: tf-metal
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - tensorflow-deps
  - pip:
    - tensorflow-macos==2.16.2
    - tensorflow-metal==1.1.0
    - matplotlib==3.7.1
    - pandas==2.0.0
    - jupyterlab==3.6.5
    - isort==5.12.0
    - black==23.3.0
    - autoflake==1.7.5
    - flake8==6.0.0
    - google-cloud-storage==2.10.0
    - tqdm==4.65.0
    - apache-beam[gcp]==2.48.0